name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        # https://help.github.com/articles/virtual-environments-for-github-actions
        platform:
          # - ubuntu-16.04
          # - ubuntu-20.04
          - ubuntu-latest  # ubuntu-18.04
          # - macos-latest  # macOS-10.14
          # - windows-2016
          # - windows-latest  # windows-2019
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox